name: flutter_dasar_dcg
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets :
    - images/
 #  - images/android.png

  fonts:
  - family: Oswald
    fonts:
      - asset: fonts/Oswald/Oswald-Regular.ttf

# untuk daftar folder images/ biar gak satu persatu kita daftarin gambar yang ingin kita masukan.
# hati hati soal indentasi nya
